content_fields:
- generic
- more_info
- reason
- resolution
- summary

plugin_fields:
- name

metadata_fields:
- category
- description
- impact
- likelihood
- node_id
- product_code
- publish_date
- python_module
- reboot_required
- role
- severity
- status
- tags

derived_fields:
- rule_id
- error_key
- plugin

interpolated_fields:
- reason
- resolution

non_null_fields:
- product_code
- role

system_types:
    rhel:
    - host
    docker:
    - container
    - host
    - image
    osp:
    - compute
    - controller
    - director
    rhev:
    - hypervisor
    - manager
    ceph:
    - osd
    - mon

impact:
    Best Practice: 1
    Boot Failure: 3
    Cluster Availability: 2
    Compatibility Error: 2
    Container Creation Failure: 2
    Container Inoperation: 3
    Data Loss: 4
    Database Performance Loss: 2
    Database Inconsistency: 4
    Decreased Security: 2
    Denial Of Service: 3
    Diagnostics Failure: 1
    Docker Metadata Inconsistency: 2
    Filesystem Corruption: 2
    Hardening: 1
    Hung Task: 2
    Inaccessible Storage: 3
    Information Disclosure: 3
    Insecure Encryption: 2
    Invalid Configuration: 1
    Kernel Panic: 3
    Local Privilege Escalation: 2
    Local Vulnerability: 2
    Malware Detected: 3
    Man In The Middle: 4
    Management Availability: 2
    Network Connectivity Loss: 3
    Network Performance Loss: 2
    Packet Loss: 2
    Remote Vulnerability: 4
    Session Decryption Vulnerability: 3
    Service Crash: 2
    Service Inoperation: 2
    Storage Excessive Consumption: 2
    Storage Performance Loss: 2
    Suspicious Activity: 2
    System Performance Loss: 2
    System Stability Loss: 3
    Unsupported Packet: 1
    VM Clone Failure: 2
    VM Crash: 2
    VM Migration Failure: 3
    VM Performance Loss: 2
    VM Start Failure: 3
    Kdump Fail: 1
    Application Hang: 2
    Service Inoperative: 2
    null: 1  # Default for when no impact is set
